/**
 * Standard error codes for the ClubVantage API
 * Format: {DOMAIN}_{ACTION}_{REASON}
 */

// Authentication & Authorization
export const AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS';
export const AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED';
export const AUTH_INSUFFICIENT_PERMISSIONS = 'AUTH_INSUFFICIENT_PERMISSIONS';
export const AUTH_SESSION_INVALID = 'AUTH_SESSION_INVALID';

// Member Errors
export const MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND';
export const MEMBER_ALREADY_EXISTS = 'MEMBER_ALREADY_EXISTS';
export const MEMBER_SUSPENDED = 'MEMBER_SUSPENDED';
export const MEMBER_INACTIVE = 'MEMBER_INACTIVE';

// Billing Errors
export const INVOICE_NOT_FOUND = 'INVOICE_NOT_FOUND';
export const INVOICE_ALREADY_PAID = 'INVOICE_ALREADY_PAID';
export const INVOICE_ALREADY_VOIDED = 'INVOICE_ALREADY_VOIDED';
export const INVOICE_CREATE_NO_MEMBER = 'INVOICE_CREATE_NO_MEMBER';
export const PAYMENT_FAILED = 'PAYMENT_FAILED';
export const PAYMENT_AMOUNT_EXCEEDS_BALANCE = 'PAYMENT_AMOUNT_EXCEEDS_BALANCE';
export const RECEIPT_NOT_FOUND = 'RECEIPT_NOT_FOUND';
export const CREDIT_LIMIT_EXCEEDED = 'CREDIT_LIMIT_EXCEEDED';

// Golf Errors
export const TEE_TIME_NOT_FOUND = 'TEE_TIME_NOT_FOUND';
export const TEE_TIME_BLOCKED = 'TEE_TIME_BLOCKED';
export const TEE_TIME_FULLY_BOOKED = 'TEE_TIME_FULLY_BOOKED';
export const TEE_TIME_BEING_BOOKED = 'TEE_TIME_BEING_BOOKED';
export const TEE_TIME_ALREADY_CANCELLED = 'TEE_TIME_ALREADY_CANCELLED';
export const TEE_TIME_WRONG_STATUS = 'TEE_TIME_WRONG_STATUS';
export const COURSE_NOT_FOUND = 'COURSE_NOT_FOUND';
export const SCHEDULE_NOT_FOUND = 'SCHEDULE_NOT_FOUND';
export const SCHEDULE_OVERLAP = 'SCHEDULE_OVERLAP';
export const BLOCK_NOT_FOUND = 'BLOCK_NOT_FOUND';
export const BLOCK_HAS_BOOKINGS = 'BLOCK_HAS_BOOKINGS';
export const PLAYER_NOT_FOUND = 'PLAYER_NOT_FOUND';
export const MAX_PLAYERS_EXCEEDED = 'MAX_PLAYERS_EXCEEDED';

// Facility Errors
export const FACILITY_NOT_FOUND = 'FACILITY_NOT_FOUND';
export const BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND';
export const BOOKING_CONFLICT = 'BOOKING_CONFLICT';
export const BOOKING_ALREADY_CANCELLED = 'BOOKING_ALREADY_CANCELLED';

// Equipment Errors
export const EQUIPMENT_NOT_FOUND = 'EQUIPMENT_NOT_FOUND';
export const EQUIPMENT_NOT_AVAILABLE = 'EQUIPMENT_NOT_AVAILABLE';
export const EQUIPMENT_ALREADY_ASSIGNED = 'EQUIPMENT_ALREADY_ASSIGNED';

// POS Errors
export const OUTLET_NOT_FOUND = 'OUTLET_NOT_FOUND';
export const SHIFT_NOT_FOUND = 'SHIFT_NOT_FOUND';
export const SHIFT_ALREADY_OPEN = 'SHIFT_ALREADY_OPEN';
export const SHIFT_ALREADY_CLOSED = 'SHIFT_ALREADY_CLOSED';
export const CART_NOT_FOUND = 'CART_NOT_FOUND';
export const LINE_ITEM_NOT_FOUND = 'LINE_ITEM_NOT_FOUND';

// AR Statement Errors
export const STATEMENT_PERIOD_NOT_FOUND = 'STATEMENT_PERIOD_NOT_FOUND';
export const STATEMENT_PERIOD_CLOSED = 'STATEMENT_PERIOD_CLOSED';
export const STATEMENT_PERIOD_EXISTS = 'STATEMENT_PERIOD_EXISTS';
export const STATEMENT_RUN_NOT_FOUND = 'STATEMENT_RUN_NOT_FOUND';
export const STATEMENT_RUN_IN_PROGRESS = 'STATEMENT_RUN_IN_PROGRESS';

// General Errors
export const RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';
export const RESOURCE_CONFLICT = 'RESOURCE_CONFLICT';
export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const OPERATION_NOT_ALLOWED = 'OPERATION_NOT_ALLOWED';
export const INTERNAL_ERROR = 'INTERNAL_ERROR';

/**
 * Error code type union
 */
export type ErrorCode =
  | typeof AUTH_INVALID_CREDENTIALS
  | typeof AUTH_TOKEN_EXPIRED
  | typeof AUTH_INSUFFICIENT_PERMISSIONS
  | typeof AUTH_SESSION_INVALID
  | typeof MEMBER_NOT_FOUND
  | typeof MEMBER_ALREADY_EXISTS
  | typeof MEMBER_SUSPENDED
  | typeof MEMBER_INACTIVE
  | typeof INVOICE_NOT_FOUND
  | typeof INVOICE_ALREADY_PAID
  | typeof INVOICE_ALREADY_VOIDED
  | typeof INVOICE_CREATE_NO_MEMBER
  | typeof PAYMENT_FAILED
  | typeof PAYMENT_AMOUNT_EXCEEDS_BALANCE
  | typeof RECEIPT_NOT_FOUND
  | typeof CREDIT_LIMIT_EXCEEDED
  | typeof TEE_TIME_NOT_FOUND
  | typeof TEE_TIME_BLOCKED
  | typeof TEE_TIME_FULLY_BOOKED
  | typeof TEE_TIME_BEING_BOOKED
  | typeof TEE_TIME_ALREADY_CANCELLED
  | typeof TEE_TIME_WRONG_STATUS
  | typeof COURSE_NOT_FOUND
  | typeof SCHEDULE_NOT_FOUND
  | typeof SCHEDULE_OVERLAP
  | typeof BLOCK_NOT_FOUND
  | typeof BLOCK_HAS_BOOKINGS
  | typeof PLAYER_NOT_FOUND
  | typeof MAX_PLAYERS_EXCEEDED
  | typeof FACILITY_NOT_FOUND
  | typeof BOOKING_NOT_FOUND
  | typeof BOOKING_CONFLICT
  | typeof BOOKING_ALREADY_CANCELLED
  | typeof EQUIPMENT_NOT_FOUND
  | typeof EQUIPMENT_NOT_AVAILABLE
  | typeof EQUIPMENT_ALREADY_ASSIGNED
  | typeof OUTLET_NOT_FOUND
  | typeof SHIFT_NOT_FOUND
  | typeof SHIFT_ALREADY_OPEN
  | typeof SHIFT_ALREADY_CLOSED
  | typeof CART_NOT_FOUND
  | typeof LINE_ITEM_NOT_FOUND
  | typeof STATEMENT_PERIOD_NOT_FOUND
  | typeof STATEMENT_PERIOD_CLOSED
  | typeof STATEMENT_PERIOD_EXISTS
  | typeof STATEMENT_RUN_NOT_FOUND
  | typeof STATEMENT_RUN_IN_PROGRESS
  | typeof RESOURCE_NOT_FOUND
  | typeof RESOURCE_CONFLICT
  | typeof VALIDATION_ERROR
  | typeof OPERATION_NOT_ALLOWED
  | typeof INTERNAL_ERROR;
