import { subHours, subDays, subMinutes } from 'date-fns'
import type {
  User,
  Role,
  PermissionSection,
  Session,
  ActivityEntry,
  PasswordPolicy,
  SessionPolicy,
  TwoFactorPolicy,
  LockoutPolicy,
} from './types'

export const mockRoles: Role[] = [
  {
    id: 'sys-1',
    name: 'Super Admin',
    description: 'Full system access. Cannot be modified or deleted.',
    permissionCount: 47,
    userCount: 2,
    isSystem: true,
    permissions: ['*'],
  },
  {
    id: 'sys-2',
    name: 'Manager',
    description: 'All operations except settings administration',
    permissionCount: 38,
    userCount: 3,
    isSystem: true,
    permissions: [],
  },
  {
    id: 'sys-3',
    name: 'Accountant',
    description: 'Billing, Reports, WHT verification',
    permissionCount: 15,
    userCount: 2,
    isSystem: true,
    permissions: [],
  },
  {
    id: 'sys-4',
    name: 'Front Desk',
    description: 'Members view, check-in, basic booking',
    permissionCount: 12,
    userCount: 5,
    isSystem: true,
    permissions: [],
  },
  {
    id: 'sys-5',
    name: 'Booking Coordinator',
    description: 'Full booking management',
    permissionCount: 18,
    userCount: 2,
    isSystem: true,
    permissions: [],
  },
  {
    id: 'sys-6',
    name: 'Membership Admin',
    description: 'Full member management',
    permissionCount: 22,
    userCount: 1,
    isSystem: true,
    permissions: [],
  },
  {
    id: 'sys-7',
    name: 'View Only',
    description: 'Read access to all sections',
    permissionCount: 20,
    userCount: 4,
    isSystem: true,
    permissions: [],
  },
  {
    id: 'cust-1',
    name: 'Golf Coordinator',
    description: 'Manages golf bookings and pro shop',
    permissionCount: 18,
    userCount: 3,
    isSystem: false,
    permissions: ['golf.teesheet.view', 'golf.teesheet.manage', 'golf.proshop.access'],
  },
]

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john@club.com',
    phone: '+66 89 123 4567',
    roles: [mockRoles[0]!],
    status: 'active',
    lastLogin: new Date(),
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Jane Doe',
    email: 'jane@club.com',
    phone: '+66 89 234 5678',
    roles: [mockRoles[1]!, mockRoles[4]!],
    status: 'active',
    lastLogin: subHours(new Date(), 2),
    createdAt: new Date('2024-02-01'),
  },
  {
    id: '3',
    name: 'Bob Wilson',
    email: 'bob@club.com',
    phone: '+66 89 345 6789',
    roles: [mockRoles[3]!],
    status: 'inactive',
    lastLogin: subDays(new Date(), 30),
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '4',
    name: 'Alice Chen',
    email: 'alice@club.com',
    phone: '+66 89 456 7890',
    roles: [mockRoles[2]!],
    status: 'active',
    lastLogin: subMinutes(new Date(), 45),
    createdAt: new Date('2024-03-01'),
  },
  {
    id: '5',
    name: 'Mike Johnson',
    email: 'mike@club.com',
    roles: [],
    status: 'locked',
    lastLogin: subDays(new Date(), 7),
    createdAt: new Date('2024-02-15'),
  },
  {
    id: '6',
    name: 'Sarah Williams',
    email: 'sarah@club.com',
    phone: '+66 89 567 8901',
    roles: [mockRoles[5]!],
    status: 'active',
    lastLogin: subHours(new Date(), 5),
    createdAt: new Date('2024-03-10'),
  },
  {
    id: '7',
    name: 'Tom Brown',
    email: 'tom@club.com',
    roles: [mockRoles[6]!],
    status: 'active',
    lastLogin: subDays(new Date(), 2),
    createdAt: new Date('2024-02-20'),
  },
]

export const mockSessions: Session[] = [
  {
    id: 's1',
    device: 'macOS',
    browser: 'Chrome 120',
    ip: '192.168.1.1',
    lastActivity: new Date(),
    current: true,
  },
  {
    id: 's2',
    device: 'iOS 17',
    browser: 'Safari',
    ip: '192.168.1.2',
    lastActivity: subHours(new Date(), 2),
    current: false,
  },
]

export const mockPermissionSections: PermissionSection[] = [
  {
    id: 'members',
    name: 'Members',
    permissions: [
      { code: 'members.directory.view', name: 'View member directory', description: 'View the member list and search', section: 'members' },
      { code: 'members.profile.view', name: 'View member detail', description: 'View individual member profiles', section: 'members' },
      { code: 'members.profile.create', name: 'Create new member', description: 'Create new member accounts', section: 'members' },
      { code: 'members.profile.edit', name: 'Edit member profile', description: 'Edit member personal information', section: 'members' },
      { code: 'members.status.change', name: 'Change member status', description: 'Activate, suspend, or cancel members', section: 'members' },
      { code: 'members.contract.view', name: 'View member contract', description: 'View membership contracts', section: 'members' },
      { code: 'members.contract.manage', name: 'Manage member contract', description: 'Add, edit, or remove charges', section: 'members' },
      { code: 'members.application.view', name: 'View applications', description: 'View membership applications', section: 'members' },
      { code: 'members.application.review', name: 'Review applications', description: 'Process membership applications', section: 'members' },
      { code: 'members.application.approve', name: 'Approve applications', description: 'Board approval vote on applications', section: 'members' },
    ],
  },
  {
    id: 'billing',
    name: 'Billing',
    permissions: [
      { code: 'billing.invoice.view', name: 'View invoices', description: 'View invoice list and details', section: 'billing' },
      { code: 'billing.invoice.create', name: 'Create invoices', description: 'Create new invoices', section: 'billing' },
      { code: 'billing.invoice.edit', name: 'Edit invoices', description: 'Edit draft invoices', section: 'billing' },
      { code: 'billing.invoice.void', name: 'Void invoices', description: 'Void issued invoices', section: 'billing' },
      { code: 'billing.receipt.view', name: 'View receipts', description: 'View receipt list and details', section: 'billing' },
      { code: 'billing.receipt.create', name: 'Create receipts', description: 'Process payments and create receipts', section: 'billing' },
      { code: 'billing.receipt.void', name: 'Void receipts', description: 'Void issued receipts', section: 'billing' },
      { code: 'billing.wht.verify', name: 'Verify WHT', description: 'Verify withholding tax certificates', section: 'billing' },
      { code: 'billing.suspension.override', name: 'Override suspension', description: 'Override member suspension status', section: 'billing' },
    ],
  },
  {
    id: 'portal',
    name: 'Portal',
    permissions: [
      { code: 'portal.access', name: 'Access member portal', description: 'Access the member self-service portal', section: 'portal' },
    ],
  },
  {
    id: 'reports',
    name: 'Reports',
    permissions: [
      { code: 'reports.dashboard.view', name: 'View dashboard', description: 'View manager dashboard', section: 'reports' },
      { code: 'reports.financial.view', name: 'View financial reports', description: 'View financial and revenue reports', section: 'reports' },
      { code: 'reports.receivables.view', name: 'View A/R reports', description: 'View accounts receivable reports', section: 'reports' },
      { code: 'reports.membership.view', name: 'View membership reports', description: 'View membership statistics', section: 'reports' },
      { code: 'reports.export', name: 'Export reports', description: 'Export report data to CSV/Excel', section: 'reports' },
      { code: 'reports.schedule', name: 'Schedule reports', description: 'Schedule automated report delivery', section: 'reports' },
    ],
  },
  {
    id: 'settings',
    name: 'Settings',
    permissions: [
      { code: 'settings.view', name: 'View settings', description: 'View settings (read-only)', section: 'settings' },
      { code: 'settings.profile.edit', name: 'Edit club profile', description: 'Edit club information', section: 'settings' },
      { code: 'settings.organization.manage', name: 'Manage organization', description: 'Manage outlets and centers', section: 'settings' },
      { code: 'settings.gl.configure', name: 'Configure GL', description: 'Configure GL mapping', section: 'settings' },
      { code: 'settings.billing.manage', name: 'Manage billing', description: 'Configure billing defaults', section: 'settings' },
      { code: 'settings.localization.manage', name: 'Manage localization', description: 'Configure language and currency', section: 'settings' },
      { code: 'settings.templates.manage', name: 'Manage templates', description: 'Manage notification templates', section: 'settings' },
      { code: 'settings.branding.manage', name: 'Manage branding', description: 'Configure branding', section: 'settings' },
      { code: 'settings.integrations.manage', name: 'Manage integrations', description: 'Configure integrations', section: 'settings' },
      { code: 'settings.lookups.manage', name: 'Manage lookups', description: 'Manage lookup values', section: 'settings' },
      { code: 'settings.audit.view', name: 'View audit config', description: 'View audit configuration', section: 'settings' },
    ],
  },
  {
    id: 'users',
    name: 'Users',
    permissions: [
      { code: 'users.directory.view', name: 'View user list', description: 'View user directory', section: 'users' },
      { code: 'users.account.create', name: 'Create users', description: 'Create user accounts', section: 'users' },
      { code: 'users.account.edit', name: 'Edit users', description: 'Edit user accounts', section: 'users' },
      { code: 'users.account.deactivate', name: 'Deactivate users', description: 'Deactivate user accounts', section: 'users' },
      { code: 'users.roles.view', name: 'View roles', description: 'View role list', section: 'users' },
      { code: 'users.roles.manage', name: 'Manage roles', description: 'Create and edit roles', section: 'users' },
      { code: 'users.permissions.view', name: 'View permissions', description: 'View permission catalog', section: 'users' },
      { code: 'users.security.manage', name: 'Manage security', description: 'Configure security policies', section: 'users' },
      { code: 'users.activity.view', name: 'View activity', description: 'View activity logs', section: 'users' },
      { code: 'users.sessions.manage', name: 'Manage sessions', description: 'Manage active sessions', section: 'users' },
    ],
  },
]

export const mockActivityEntries: ActivityEntry[] = [
  {
    id: 'a1',
    timestamp: new Date(),
    user: { id: '1', name: 'John Smith' },
    action: 'login',
    ip: '192.168.1.1',
    details: { browser: 'Chrome 120', os: 'macOS' },
  },
  {
    id: 'a2',
    timestamp: subMinutes(new Date(), 15),
    user: { id: '2', name: 'Jane Doe' },
    action: 'create',
    target: 'Invoice #INV-2024-0042',
    ip: '192.168.1.2',
    details: { description: 'Created invoice for Member: John Doe', amount: 15000, browser: 'Safari 17', os: 'iOS 17' },
  },
  {
    id: 'a3',
    timestamp: subMinutes(new Date(), 30),
    user: { id: '4', name: 'Alice Chen' },
    action: 'update',
    target: 'Member #M-1234',
    ip: '192.168.1.3',
    details: { description: 'Updated member status to Active', browser: 'Firefox 120', os: 'Windows 11' },
  },
  {
    id: 'a4',
    timestamp: subHours(new Date(), 1),
    user: { id: '1', name: 'John Smith' },
    action: 'delete',
    target: 'Role: Test Role',
    ip: '192.168.1.1',
    details: { description: 'Deleted custom role' },
  },
  {
    id: 'a5',
    timestamp: subHours(new Date(), 2),
    user: { id: '6', name: 'Sarah Williams' },
    action: 'view',
    target: 'Financial Report Q4 2024',
    ip: '192.168.1.4',
    details: { browser: 'Chrome 120', os: 'Windows 11' },
  },
  {
    id: 'a6',
    timestamp: subHours(new Date(), 3),
    user: { id: '2', name: 'Jane Doe' },
    action: 'export',
    target: 'Member Directory',
    ip: '192.168.1.2',
    details: { format: 'CSV', records: 1250 },
  },
  {
    id: 'a7',
    timestamp: subHours(new Date(), 4),
    user: { id: '3', name: 'Bob Wilson' },
    action: 'logout',
    ip: '192.168.1.5',
    details: { sessionDuration: '4h 32m' },
  },
]

export const defaultPasswordPolicy: PasswordPolicy = {
  minLength: 12,
  requireUppercase: true,
  requireLowercase: true,
  requireNumber: true,
  requireSpecialChar: false,
  expirationDays: 90,
  historyCount: 5,
}

export const defaultSessionPolicy: SessionPolicy = {
  idleTimeoutMinutes: 30,
  maxConcurrentSessions: 3,
  allowRememberDevice: true,
  rememberDeviceDays: 30,
}

export const defaultTwoFactorPolicy: TwoFactorPolicy = {
  enabled: false,
  required: false,
  allowAuthenticator: true,
  allowSms: false,
}

export const defaultLockoutPolicy: LockoutPolicy = {
  failedAttemptsThreshold: 5,
  lockoutDurationMinutes: 30,
  autoUnlock: true,
}
