// Client
export {
  initializeClient,
  getClient,
  getWSClient,
  graphqlFetcher,
  request,
  subscribe,
  closeClients,
  GraphQLClient,
  type ApiClientConfig,
} from './client';

// Provider
export { ApiProvider, type ApiProviderProps } from './provider';

// Types - export all types from the types module
export * from './types';

// Hooks - only export hooks (not re-exported types) from hooks/generated
// Types are already exported from ./types above
export {
  // Billing hooks
  useGetBillingStatsQuery,
  useInfiniteGetBillingStatsQuery,
  useGetMyInvoicesQuery,
  useInfiniteGetMyInvoicesQuery,
  useGetInvoicesQuery,
  useInfiniteGetInvoicesQuery,
  useGetInvoiceQuery,
  useInfiniteGetInvoiceQuery,
  useGetMemberTransactionsQuery,
  useInfiniteGetMemberTransactionsQuery,
  useGenerateStatementQuery,
  useInfiniteGenerateStatementQuery,
  useCreateInvoiceMutation,
  useSendInvoiceMutation,
  useVoidInvoiceMutation,
  useRecordPaymentMutation,
  // Booking hooks
  useGetBookingsQuery,
  useInfiniteGetBookingsQuery,
  useGetBookingQuery,
  useInfiniteGetBookingQuery,
  useGetBookingStatsQuery,
  useInfiniteGetBookingStatsQuery,
  useGetCalendarDayQuery,
  useInfiniteGetCalendarDayQuery,
  useCreateBookingMutation,
  useCancelBookingMutation,
  useRescheduleBookingMutation,
  useCheckInBookingMutation,
  // Facility hooks
  useGetFacilitiesQuery,
  useInfiniteGetFacilitiesQuery,
  useCreateFacilityMutation,
  useUpdateFacilityMutation,
  useDeleteFacilityMutation,
  // Service hooks
  useGetServicesQuery,
  useInfiniteGetServicesQuery,
  useCreateServiceMutation,
  useUpdateServiceMutation,
  useDeleteServiceMutation,
  // Staff hooks
  useGetBookingStaffQuery,
  useInfiniteGetBookingStaffQuery,
  useCreateStaffMemberMutation,
  useUpdateStaffMemberMutation,
  useDeleteStaffMemberMutation,
  // Waitlist hooks
  useGetWaitlistQuery,
  useInfiniteGetWaitlistQuery,
  useJoinWaitlistMutation,
  useRemoveFromWaitlistMutation,
  useSendWaitlistOfferMutation,
  useAcceptWaitlistOfferMutation,
  useDeclineWaitlistOfferMutation,
  // Golf hooks
  useGetTeeSheetQuery,
  useInfiniteGetTeeSheetQuery,
  useGetCoursesQuery,
  useInfiniteGetCoursesQuery,
  useGetTeeTimeQuery,
  useInfiniteGetTeeTimeQuery,
  useGetTeeTimesQuery,
  useInfiniteGetTeeTimesQuery,
  useGetWeekViewOccupancyQuery,
  useInfiniteGetWeekViewOccupancyQuery,
  useSearchCaddiesQuery,
  useInfiniteSearchCaddiesQuery,
  useCreateTeeTimeMutation,
  useUpdateTeeTimeMutation,
  useUpdateTeeTimePlayersMutation,
  useUpdatePlayerRentalStatusMutation,
  useCheckInTeeTimeMutation,
  useCancelTeeTimeMutation,
  useMoveTeeTimeMutation,
  // Golf Check-In hooks
  useGetFlightCheckInInfoQuery,
  useInfiniteGetFlightCheckInInfoQuery,
  useGetPlayerPaymentInfoQuery,
  useInfiniteGetPlayerPaymentInfoQuery,
  useGetFlightPaymentSummaryQuery,
  useInfiniteGetFlightPaymentSummaryQuery,
  useGetStarterTicketQuery,
  useInfiniteGetStarterTicketQuery,
  useGetStarterTicketByTeeTimeQuery,
  useInfiniteGetStarterTicketByTeeTimeQuery,
  useGetTicketHtmlQuery,
  useInfiniteGetTicketHtmlQuery,
  useGetReceiptHtmlQuery,
  useInfiniteGetReceiptHtmlQuery,
  useValidateTicketQuery,
  useInfiniteValidateTicketQuery,
  useGetCheckInHistoryQuery,
  useInfiniteGetCheckInHistoryQuery,
  useGetDailyCheckInReportQuery,
  useInfiniteGetDailyCheckInReportQuery,
  useGetCheckInPaymentMethodsQuery,
  useInfiniteGetCheckInPaymentMethodsQuery,
  useGetGolfCheckInSettingsQuery,
  useInfiniteGetGolfCheckInSettingsQuery,
  useGetProShopCategoriesQuery,
  useInfiniteGetProShopCategoriesQuery,
  useGetProShopProductsQuery,
  useInfiniteGetProShopProductsQuery,
  useAddLineItemMutation,
  useRemoveLineItemMutation,
  useProcessSettlementMutation,
  useCheckInFlightMutation,
  useCheckInAllPlayersMutation,
  useSettleAllPlayersMutation,
  useUndoCheckInMutation,
  useGenerateStarterTicketMutation,
  usePrintStarterTicketMutation,
  useCreateProShopCategoryMutation,
  useUpdateProShopCategoryMutation,
  useDeleteProShopCategoryMutation,
  useCreateProShopProductMutation,
  useUpdateProShopProductMutation,
  useDeleteProShopProductMutation,
  // Shopping Cart hooks
  useGetTeeTimeCartsQuery,
  useInfiniteGetTeeTimeCartsQuery,
  useGetSlotCartQuery,
  useInfiniteGetSlotCartQuery,
  useGetBatchTotalQuery,
  useInfiniteGetBatchTotalQuery,
  useIsTeeTimeFullySettledQuery,
  useInfiniteIsTeeTimeFullySettledQuery,
  useGetCartDraftQuery,
  useInfiniteGetCartDraftQuery,
  useHasDraftQuery,
  useInfiniteHasDraftQuery,
  useTransferLineItemMutation,
  useUndoTransferMutation,
  useProcessBatchPaymentMutation,
  useCheckInSlotsMutation,
  useSaveCartDraftMutation,
  useClearCartDraftMutation,
  useUpdateLineItemQuantityMutation,
  useBulkRemoveLineItemsMutation,
  useBulkTransferLineItemsMutation,
  usePayLineItemsMutation,
  // Discount hooks
  useGetDiscountsQuery,
  useInfiniteGetDiscountsQuery,
  useGetActiveDiscountsQuery,
  useInfiniteGetActiveDiscountsQuery,
  useGetDiscountQuery,
  useInfiniteGetDiscountQuery,
  useGetDiscountByCodeQuery,
  useInfiniteGetDiscountByCodeQuery,
  useValidateDiscountQuery,
  useInfiniteValidateDiscountQuery,
  useGetLineItemDiscountsQuery,
  useInfiniteGetLineItemDiscountsQuery,
  useGetTransactionDiscountsQuery,
  useInfiniteGetTransactionDiscountsQuery,
  useCreateDiscountMutation,
  useUpdateDiscountMutation,
  useDeleteDiscountMutation,
  useApplyDiscountMutation,
  useApplyDiscountByCodeMutation,
  useApproveDiscountMutation,
  useRemoveAppliedDiscountMutation,
  // Member hooks
  useGetMyMemberQuery,
  useInfiniteGetMyMemberQuery,
  useGetMembersQuery,
  useInfiniteGetMembersQuery,
  useGetMemberQuery,
  useInfiniteGetMemberQuery,
  useGetMemberStatsQuery,
  useInfiniteGetMemberStatsQuery,
  useCreateMemberMutation,
  useUpdateMemberMutation,
  useDeleteMemberMutation,
  useChangeMemberStatusMutation,
  // Dependent hooks
  useCreateDependentMutation,
  useUpdateDependentMutation,
  useDeleteDependentMutation,
  // Address hooks
  useCreateMemberAddressMutation,
  useUpdateMemberAddressMutation,
  useDeleteMemberAddressMutation,
  // Application hooks
  useGetApplicationsQuery,
  useInfiniteGetApplicationsQuery,
  useGetApplicationQuery,
  useInfiniteGetApplicationQuery,
  useGetApplicationStatsQuery,
  useInfiniteGetApplicationStatsQuery,
  useCreateApplicationMutation,
  useUpdateApplicationMutation,
  useChangeApplicationStatusMutation,
  // Credit Limit hooks
  useCheckMemberCreditQuery,
  useInfiniteCheckMemberCreditQuery,
  useGetMemberCreditStatusQuery,
  useInfiniteGetMemberCreditStatusQuery,
  useGetMemberCreditSettingsQuery,
  useInfiniteGetMemberCreditSettingsQuery,
  useGetMemberCreditOverridesQuery,
  useInfiniteGetMemberCreditOverridesQuery,
  useGetMemberCreditOverrideHistoryQuery,
  useInfiniteGetMemberCreditOverrideHistoryQuery,
  useGetMembersAtCreditRiskQuery,
  useInfiniteGetMembersAtCreditRiskQuery,
  useCreateCreditOverrideMutation,
  useRevertCreditOverrideMutation,
  useUpdateMemberCreditSettingsMutation,
  // Cash Drawer hooks
  useGetCashDrawersQuery,
  useInfiniteGetCashDrawersQuery,
  useGetCashDrawerQuery,
  useInfiniteGetCashDrawerQuery,
  useGetCurrentShiftQuery,
  useInfiniteGetCurrentShiftQuery,
  useGetCashDrawerShiftQuery,
  useInfiniteGetCashDrawerShiftQuery,
  useGetShiftSummaryQuery,
  useInfiniteGetShiftSummaryQuery,
  useGetShiftHistoryQuery,
  useInfiniteGetShiftHistoryQuery,
  useGetShiftMovementsQuery,
  useInfiniteGetShiftMovementsQuery,
  useCreateCashDrawerMutation,
  useUpdateCashDrawerMutation,
  useOpenShiftMutation,
  useCloseShiftMutation,
  useSuspendShiftMutation,
  useResumeShiftMutation,
  useRecordCashMovementMutation,
  // EOD Settlement hooks
  useGetTodaySettlementQuery,
  useInfiniteGetTodaySettlementQuery,
  useGetSettlementQuery,
  useInfiniteGetSettlementQuery,
  useGetSettlementByDateQuery,
  useInfiniteGetSettlementByDateQuery,
  useGetSettlementsQuery,
  useInfiniteGetSettlementsQuery,
  useGetSettlementSummaryQuery,
  useInfiniteGetSettlementSummaryQuery,
  useGetSettlementExceptionsQuery,
  useInfiniteGetSettlementExceptionsQuery,
  useOpenDayMutation,
  useSubmitSettlementForReviewMutation,
  useCloseSettlementMutation,
  useReopenSettlementMutation,
  useUpdateSettlementTotalsMutation,
  useRecordCashCountMutation,
  useRecalculateSettlementTotalsMutation,
  useCreateSettlementExceptionMutation,
  useResolveSettlementExceptionMutation,
  // Minimum Spend hooks
  useGetMinimumSpendRequirementsQuery,
  useInfiniteGetMinimumSpendRequirementsQuery,
  useGetMinimumSpendRequirementQuery,
  useInfiniteGetMinimumSpendRequirementQuery,
  useGetMemberMinimumSpendsQuery,
  useInfiniteGetMemberMinimumSpendsQuery,
  useGetMemberMinimumSpendQuery,
  useInfiniteGetMemberMinimumSpendQuery,
  useGetCurrentMemberSpendQuery,
  useInfiniteGetCurrentMemberSpendQuery,
  useCreateMinimumSpendRequirementMutation,
  useUpdateMinimumSpendRequirementMutation,
  useDeleteMinimumSpendRequirementMutation,
  useRecordMinimumSpendMutation,
  useResolveMinimumSpendShortfallMutation,
  useExemptMemberFromMinimumSpendMutation,
  useRemoveMinimumSpendExemptionMutation,
  useCloseMinimumSpendPeriodMutation,
  useRecalculateMemberSpendMutation,
  // Sub-Account hooks
  useGetSubAccountsQuery,
  useInfiniteGetSubAccountsQuery,
  useGetSubAccountQuery,
  useInfiniteGetSubAccountQuery,
  useGetMemberSubAccountsQuery,
  useInfiniteGetMemberSubAccountsQuery,
  useCheckSubAccountLimitQuery,
  useInfiniteCheckSubAccountLimitQuery,
  useGetSubAccountTransactionsQuery,
  useInfiniteGetSubAccountTransactionsQuery,
  useCreateSubAccountMutation,
  useUpdateSubAccountMutation,
  useVerifySubAccountPinMutation,
  useChangeSubAccountPinMutation,
  useChangeSubAccountStatusMutation,
  useUnlockSubAccountPinMutation,
  useDeleteSubAccountMutation,
  useRecordSubAccountTransactionMutation,
  useResetSubAccountSpendingMutation,
  // Stored Payment hooks
  useGetMemberPaymentMethodsQuery,
  useInfiniteGetMemberPaymentMethodsQuery,
  useGetPaymentMethodQuery,
  useInfiniteGetPaymentMethodQuery,
  useGetMemberAutoPaySettingQuery,
  useInfiniteGetMemberAutoPaySettingQuery,
  useGetMemberAutoPayHistoryQuery,
  useInfiniteGetMemberAutoPayHistoryQuery,
  useGetInvoiceAutoPayAttemptsQuery,
  useInfiniteGetInvoiceAutoPayAttemptsQuery,
  useAddPaymentMethodMutation,
  useUpdatePaymentMethodMutation,
  useRemovePaymentMethodMutation,
  useSetDefaultPaymentMethodMutation,
  useUpsertAutoPaySettingMutation,
  useDisableAutoPayMutation,
  useProcessAutoPayMutation,
  useRetryAutoPayAttemptMutation,
  // POS Config hooks
  useGetPosConfigQuery,
  useInfiniteGetPosConfigQuery,
  useGetPosTemplatesQuery,
  useInfiniteGetPosTemplatesQuery,
  useGetPosTemplateQuery,
  useInfiniteGetPosTemplateQuery,
  useGetPosOutletsQuery,
  useInfiniteGetPosOutletsQuery,
  useGetPosOutletQuery,
  useInfiniteGetPosOutletQuery,
  useGetPosButtonRegistryQuery,
  useInfiniteGetPosButtonRegistryQuery,
  useUpsertPosTemplateMutation,
  useClonePosTemplateMutation,
  useDeletePosTemplateMutation,
  useAssignPosTemplateMutation,
  useSetPosRoleOverridesMutation,
  useUpdatePosButtonRegistryMutation,
  // Equipment hooks
  useGetEquipmentCategoriesQuery,
  useInfiniteGetEquipmentCategoriesQuery,
  useGetEquipmentCategoryQuery,
  useInfiniteGetEquipmentCategoryQuery,
  useGetEquipmentQuery,
  useInfiniteGetEquipmentQuery,
  useGetEquipmentItemQuery,
  useInfiniteGetEquipmentItemQuery,
  useGetEquipmentAvailabilityQuery,
  useInfiniteGetEquipmentAvailabilityQuery,
  useCreateEquipmentCategoryMutation,
  useUpdateEquipmentCategoryMutation,
  useDeleteEquipmentCategoryMutation,
  useCreateEquipmentMutation,
  useUpdateEquipmentMutation,
  useUpdateEquipmentStatusMutation,
  useDeleteEquipmentMutation,
  useAssignEquipmentMutation,
  useReturnEquipmentMutation,
  useReleaseEquipmentForBookingMutation,
  // Lookup hooks
  useGetLookupCategoriesQuery,
  useInfiniteGetLookupCategoriesQuery,
  useGetLookupCategoryQuery,
  useInfiniteGetLookupCategoryQuery,
  useGetLookupValuesQuery,
  useInfiniteGetLookupValuesQuery,
  useGetLookupValueQuery,
  useInfiniteGetLookupValueQuery,
  useCreateLookupValueMutation,
  useUpdateLookupValueMutation,
  useDeleteLookupValueMutation,
  useAddLookupTranslationMutation,
  useDeleteLookupTranslationMutation,
  // Document hooks
  useGetMemberDocumentsQuery,
  useInfiniteGetMemberDocumentsQuery,
  useGetDocumentQuery,
  useInfiniteGetDocumentQuery,
  useGetDocumentSignedUrlQuery,
  useInfiniteGetDocumentSignedUrlQuery,
  useUploadMemberDocumentMutation,
  useUpdateMemberDocumentMutation,
  useDeleteMemberDocumentMutation,
  useVerifyDocumentMutation,
  // AR Profile hooks
  useGetArProfilesQuery,
  useInfiniteGetArProfilesQuery,
  useGetArProfileQuery,
  useInfiniteGetArProfileQuery,
  useGetArProfileByMemberQuery,
  useInfiniteGetArProfileByMemberQuery,
  useCreateArProfileMutation,
  useUpdateArProfileMutation,
  useSuspendArProfileMutation,
  useReactivateArProfileMutation,
  useCloseArProfileMutation,
  // AR Profile Sync hooks
  useGetMembersWithoutArProfilesCountQuery,
  useInfiniteGetMembersWithoutArProfilesCountQuery,
  useGetMembersWithoutArProfilesQuery,
  useInfiniteGetMembersWithoutArProfilesQuery,
  useSyncMembersToArProfilesMutation,
  useSyncCityLedgersToArProfilesMutation,
  // Statement Period hooks
  useGetStatementPeriodsQuery,
  useInfiniteGetStatementPeriodsQuery,
  useGetStatementPeriodQuery,
  useInfiniteGetStatementPeriodQuery,
  useGetCurrentStatementPeriodQuery,
  useInfiniteGetCurrentStatementPeriodQuery,
  useCreateStatementPeriodMutation,
  useUpdateStatementPeriodMutation,
  useCloseStatementPeriodMutation,
  useReopenStatementPeriodMutation,
  useDeleteStatementPeriodMutation,
  // Statement Run hooks
  useGetStatementRunsByPeriodQuery,
  useInfiniteGetStatementRunsByPeriodQuery,
  useGetStatementRunQuery,
  useInfiniteGetStatementRunQuery,
  useStartStatementRunMutation,
  useCancelStatementRunMutation,
  // Statement hooks
  useGetStatementsByRunQuery,
  useInfiniteGetStatementsByRunQuery,
  useGetStatementQuery,
  useInfiniteGetStatementQuery,
  useGetProfileStatementsQuery,
  useInfiniteGetProfileStatementsQuery,
  useUpdateStatementDeliveryStatusMutation,
  useMarkStatementPortalViewedMutation,
} from './hooks/generated';

// Custom hooks
export { useSubscription } from './hooks/useSubscription';

// Utils
export * from './utils';

// Auth
export * from './auth';
